server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3333
    url: jdbc:mysql://47.113.221.114:3306/rent_car?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
mybatis:
 mapper-locations: classpath:com.ikun.mapper/*.xml
 type-aliases-package: com.ikun.entity
logging:
  level:
    com.ikun.dao: debug